### ISSUE TITLE
Ideas for Phase 3

### ISSUE THREAD

**Issue by Tempestyash123456** [Tempestyash123456/Evolution-in-EVs#6]
### Discussed in https://github.com/Tempestyash123456/Evolution-in-EVs/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **Tempestyash123456** February 29, 2024</sup>
What should we do in the phase 3 of our project development ?</div>

**Comment by harshraj1695** [comment]
## Extension cord for EV Charger
**EVs** as we know there are very less amount of chargers present in India for EVs so we can create an extension system of EV charger
